export const types = {
  FETCH_INBOX_STARTED: 'FETCT_INBOX_STARTED',
  FETCH_INBOX_FAILED: 'FETCT_INBOX_SUCCESS',
  FETCH_INBOX_SUCCESS: 'LOGIN_SUCCESS',

  FETCH_OUTBOX_STARTED: 'FETCH_OUTBOX_STARTED',
  FETCH_OUTBOX_FAILED: 'FETCH_OUTBOX_FAILED',
  FETCH_OUTBOX_SUCCESS: 'FETCH_OUTBOX_SUCCESS',
};

export const API_URL = 'https://api-epicmail-v2.herokuapp.com/api/v1/';
